name: Export new icons from Figma

on:
  workflow_dispatch:
    inputs:
      fileKey:
        description: Figma file key
        type: string
      page:
        description: Stringified selected page (id, name)
        type: string
        default: '{}'
      selection:
        description: Stringified array of the selected nodes (id, name)
        type: string
        default: '[]'

jobs:
  Export-icons:
    name: Export Icons
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm clean-install
      - name: Build
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
        run: npm run rebuild
