name: Release
on:
  push:
    branches:
      - main
      - beta
      - next
      - '^([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*|x)'

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm clean-install
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        if: success()
        run: npm audit signatures
      - name: Release
        if: success()
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN}}
        run: npx semantic-release
      - name: Trigger Quill Icons Park release
        if: success()
        env:
          QUILL_ICONS_PARK_WORK_FLOW_FILE: 'pr_to_inform_quill_icons_update.yaml'
          QUILL_ICONS_PARK_REPO_ORG: 'deriv-com'
          QUILL_ICONS_PARK_REPO_NAME: 'quill-icons'
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.CI_GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{env.QUILL_ICONS_PARK_REPO_ORG}}/${{env.QUILL_ICONS_PARK_REPO_NAME}}/actions/workflows/${{env.QUILL_ICONS_PARK_WORK_FLOW_FILE}}/dispatches \
            -d '{"ref":"main"}'
