name: Trigger Quill Icons Park release

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  trigger-quill-icons-park-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Quill Icons Park repository
        uses: actions/checkout@v3
        with:
          repository: deriv-com/quill-icons-park
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          path: quill-icons-park

      - name: Set up Git identity
        run: |
          git config --global user.email "quill-icons@deriv.com"
          git config --global user.name "Quill Icons"

      - name: Update version
        run: |
          cd quill-icons-park
          npm version patch -m "build: 🚀 %s installs latest quill icons"
          git push origin master
