name: Trigger Quill Icons Park release

on:
  workflow_dispatch:

jobs:
  trigger-quill-icons-park-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Quill Icons Park repository
        uses: actions/checkout@v3
        with:
          repository: deriv-com/quill-icons-park
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          path: quill-icons-park

      - name: Set up Git identity
        run: |
          git config --global user.email "quill-icons@deriv.com"
          git config --global user.name "Quill Icons"

      - name: Create pull request
        run: |
          cd quill-icons-park
          git branch -D updated-quill-icons
          git checkout -b updated-quill-icons
          npm version patch -m "build: 🚀 %s installs latest quill icons"
          git push origin updated-quill-icons
          gh pr create --B master -H updated-quill-icons --title "[Quill Icons] 🚦 Update quill icons" --body "Merge this PR to trigger build and deployment of latest quill icons"
